export const MOCK_SERVICES = [
    {
        id: "1",
        index: "01",
        title: "Приём врачей",
        shortDesc: "Консультации\nврачей различных\nспециализаций",
        cards: [
            { id: "p1", category: "Приём врачей", title: "Приём врача-терапевта (первичный)", duration: "от 30 мин", price: "4 200 ₽" },
            { id: "p2", category: "Приём врачей", title: "Приём врача-терапевта (повторный)", duration: "от 30 мин", price: "4 000 ₽" },
            { id: "p3", category: "Приём врачей", title: "Приём врача-кардиолога (первичный)", duration: "от 30 мин", price: "5 000 ₽" },
            { id: "p4", category: "Приём врачей", title: "Приём врача-кардиолога (повторный)", duration: "от 30 мин", price: "4 800 ₽" },
            { id: "p5", category: "Приём врачей", title: "Приём врача-гинеколога (первичный)", duration: "от 30 мин", price: "5 200 ₽" },
            { id: "p6", category: "Приём врачей", title: "Приём врача-гинеколога (повторный)", duration: "от 30 мин", price: "5 000 ₽" },
            { id: "p7", category: "Приём врачей", title: "Приём врача-невролога (первичный)", duration: "от 30 мин", price: "5 000 ₽" },
            { id: "p8", category: "Приём врачей", title: "Приём врача-невролога (повторный)", duration: "от 30 мин", price: "4 800 ₽" },
            { id: "p9", category: "Приём врачей", title: "Приём врача-педиатра (первичный)", duration: "от 30 мин", price: "4 400 ₽" },
            { id: "p10", category: "Приём врачей", title: "Приём врача-педиатра (повторный)", duration: "от 30 мин", price: "4 200 ₽" },
            { id: "p11", category: "Приём врачей", title: "Приём врача-психолога (первичный)", duration: "от 30 мин", price: "4 200 ₽" },
            { id: "p12", category: "Приём врачей", title: "Приём врача-психолога (повторный)", duration: "от 30 мин", price: "4 000 ₽" },
            { id: "p13", category: "Приём врачей", title: "Приём врача-гастроэнтеролога (первичный)", duration: "от 30 мин", price: "4 800 ₽" },
            { id: "p14", category: "Приём врачей", title: "Приём врача-гастроэнтеролога (повторный)", duration: "от 30 мин", price: "4 600 ₽" },
        ],
    },
    {
        id: "2",
        index: "02",
        title: "Диагностика",
        shortDesc: "УЗИ, ЭКГ\nи функциональная\nдиагностика",
        cards: [
            { id: "d1", category: "Диагностика", title: "УЗИ органов брюшной полости", duration: "от 30 мин", price: "5 800 ₽" },
            { id: "d2", category: "Диагностика", title: "УЗИ почек", duration: "от 20 мин", price: "3 200 ₽" },
            { id: "d3", category: "Диагностика", title: "УЗИ печени", duration: "от 20 мин", price: "3 200 ₽" },
            { id: "d4", category: "Диагностика", title: "УЗИ органов малого таза", duration: "от 30 мин", price: "5 800 ₽" },
            { id: "d5", category: "Диагностика", title: "ТРУЗИ", duration: "от 20 мин", price: "4 100 ₽" },
            { id: "d6", category: "Диагностика", title: "УЗИ щитовидной железы", duration: "от 20 мин", price: "4 100 ₽" },
            { id: "d7", category: "Диагностика", title: "УЗИ сосудов", duration: "от 20 мин", price: "5 300 ₽" },
            { id: "d8", category: "Диагностика", title: "УЗИ молочных желез", duration: "от 20 мин", price: "4 100 ₽" },
            { id: "d9", category: "Диагностика", title: "УЗИ сердца (ЭХО КГ)", duration: "от 30 мин", price: "6 200 ₽" },
            { id: "d10", category: "Диагностика", title: "УЗИ суставов", duration: "от 20 мин", price: "5 800 ₽" },
            { id: "d11", category: "Диагностика", title: "УЗИ беременных", duration: "от 30 мин", price: "6 100 ₽" },
            { id: "d12", category: "Диагностика", title: "ЭКГ", duration: "10 мин", price: "3 900 ₽" },
            { id: "d13", category: "Диагностика", title: "СМАД", duration: "от 15 мин", price: "7 100 ₽" },
            { id: "d14", category: "Диагностика", title: "СМ ЭКГ (холтер)", duration: "от 15 мин", price: "7 100 ₽" },
            { id: "d15", category: "Диагностика", title: "Биоимпедансометрия", duration: "от 10 мин", price: "4 100 ₽" },
        ],
    },
    {
        id: "3",
        index: "03",
        title: "Прочие услуги",
        shortDesc: "Справки\nи процедуры",
        cards: [
            { id: "o1", category: "Прочие услуги", title: "Получение справки", duration: "от 20 мин", price: "3 800 ₽" },
            { id: "o2", category: "Прочие услуги", title: "Внутривенные инфузии", duration: "от 40 мин", price: "от 4 200 ₽" },
        ],
    },
]